### ISSUE TITLE
Error essid

### ISSUE THREAD

**Issue by warecrer** [rofl0r/oneshot#7]
Error essid

**Comment by aniketstark** [comment]
> Error essid

i am also facing one of these

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/OneShot/oneshot.py", line 1214, in <module>
    args.bssid = scanner.prompt_network()
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/OneShot/oneshot.py", line 1019, in prompt_network
    networks = self.iw_scanner()
               ^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/OneShot/oneshot.py", line 1000, in iw_scanner
    essid = truncateStr(network['ESSID'], 25)
                        ~~~~~~~^^^^^^^^^
KeyError: 'ESSID'

**Comment by aniketstark** [comment]
> Error essid

i am trying to find were and how its causing 

for the period just run this script while wifif on for mobile devices sd and mtk both this is the fix of  some period

**Comment by pradeep-lit** [comment]
essid = truncateStr(network.get('ESSID', 'Unknown'), 25)
